BEGIN TRANSACTION;
CREATE TABLE "Teachers" (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`surname`	TEXT,
	`name`	TEXT,
	`patronymic`	TEXT,
	`phone`	TEXT
);
CREATE TABLE "Subjects" (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`name`	TEXT NOT NULL,
	`group`	INTEGER NOT NULL,
	`classroom`	INTEGER NOT NULL,
	`teacher`	INTEGER NOT NULL,
	FOREIGN KEY(`group`) REFERENCES 'Chats'('group'),
	FOREIGN KEY(`teacher`) REFERENCES `Teachers`(`id`)
);
CREATE TABLE "Schedule" (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`number`	INTEGER NOT NULL,
	`subject`	INTEGER NOT NULL,
	`week_day`	INTEGER NOT NULL,
	`week_parity`	INTEGER NOT NULL,
	`time_begin`	TEXT NOT NULL,
	`time_end`	TEXT NOT NULL,
	FOREIGN KEY(`subject`) REFERENCES `Subjects`(`id`)
);
CREATE TABLE `Chats` (
	`id`	INTEGER NOT NULL UNIQUE,
	`group`	INTEGER NOT NULL,
	PRIMARY KEY(id)
);
COMMIT;
